### ISSUE TITLE
Compilation of a typescript project with connect-mongo dependency fails

### ISSUE THREAD

**Issue by richjyoung** [jdesboeufs/connect-mongo#340]
This error has suddenly appeared during typescript compile, despite the fact I do not use mongoose.

node_modules/connect-mongo/src/types.d.ts(11,27): error TS2307: Cannot find module 'mongoose'.

**Comment by richjyoung** [comment]
Affected connect-mongo version is 3.1.1

**Comment by mingchuno** [comment]
@richjyoung It maybe related to this issue https://github.com/jdesboeufs/connect-mongo/issues/338
Please rollback to `3.1.0` first, it should work fine.

@guyellis would you please help take a look?

**Comment by richjyoung** [comment]
It most likely is related, however I should add that I do not use `@types/connect-mongo` either.

**Comment by guyellis** [comment]
I'll take a look.

**Comment by guyellis** [comment]
I think the solution is to include those types as dev dependencies on the project. I'll work on this later and test it locally and then do a PR.

This should not have an impact for people who don't use TypeScript.

I'd imagine that the best workarounds are:

- Use `3.1.0` - only difference with `3.1.1` is the Typescript definition.
- Add the dependencies it's asking for to your dependencies until this is updated.

**Comment by richjyoung** [comment]
Issue closed but npm still has 3.1.1 as the latest?

**Comment by mingchuno** [comment]
@richjyoung I have already published v3.1.2 to npm

**Comment by alias-mac** [comment]
@guyellis shouldn't this be in "dependencies" instead of "devDependencies"?
I believe this still causes issues because I still don't have those types installed in that package.

If you test it similar to your PR on #341 but with:
```
# checkout master of this repo
npm install --production # which is what we normally get from a dependent typescript project
npm link # the connect-mongo repo with the current master checked out.
npm link connect-mongo #on a dependent TypeScript project
```
you will see that this still fails.

@richjyoung temporarily you can probably use `"skipLibCheck": true,`.

**Comment by guyellis** [comment]
@alias-mac - It depends:

Because these @types libraries are there to support TypeScript tooling they technically shouldn't be in the dependencies. If your project is using TypeScript and this module then yes it will fail under the current setup.

The workaround that I use is to install those @types dependencies in my project's devDependencies. That way we are able to keep them out production code.

Because this is a JS (and not TS) project I think that putting them in the dependencies would be objectionable to non-TS users.

What about an explanation for TypeScript users in the Readme explaining "install those locally"? WDYT?

**Comment by escaroda** [comment]
I've had this error too.
Fixed with: `npm i -D @types/mongoose` even though I don't use mongoose in my project

```
"connect-mongo": "^3.2.0"
"mongodb": "^3.5.5"

"@types/mongodb": "^3.5.3"
"@types/mongoose": "^5.7.8"
```
